# /**
# * Loopware Online Subsystem @ DatastoreDB Dockerfile || Simple dockerfile that allows for the creation of
# * a MongoDB instance for storing all types of data
# * TODO: Implement a way of scaling
# */

services:
  mongoDBInstance:
    image: mongo:latest
    container_name: loss-datastore-storage-mongodb
    command: "mongod --port 36201"
    environment:
      # It is adviced to change the default username and password
      - MONGO_INITDB_ROOT_USERNAME=lossDatastoreMongoDB
      - MONGO_INITDB_ROOT_PASSWORD=lossDatastoreMongoDB
    volumes:
      - datastoreStorageVolume:/lossDatastoreDB:rw
    ports:
      - "36201:36201"
    restart: always
    
volumes:
  datastoreStorageVolume:
    name: loss-datastore-storage-volume