# Pull the latest node version
FROM node:latest

# Metadata
LABEL name="Authorization Server @ LOSS"
LABEL version="1.0"
LABEL description="LOSS-Authorization Server"

# Make app directory
RUN ["mkdir", "-p", "/home/$USER/loss-docker/auth-server"]

# Set the working directory
WORKDIR "/home/$USER/loss-docker/auth-server"

# Copy package.json
COPY ./package.json ./

# Install packages
RUN ["npm", "install"]

# Copy build
COPY ./build/ ./

# Set enviroment variables
# Client ID: 9aNodtMGO0QpE7iivB6OYmFxSOzWqjtKRGLJI36Ls8HT4lPjXu4Ql6XCm4dbg+PgTN8YxF7fXAA6ehEOntJSwg==
ENV PORT=8081
ENV SERVER_ACCESS_TOKEN=zEAYGHnQgshrT+hAiE1IOG9wJDQZpfd3JaxDjdbO6kU=
ENV SERVER_REFRESH_TOKEN=9gydVYrINijA8h3vOal3Icg/0InEoS5JZYaXLft9YdYiVFA9xcY+SpYsIz1D04/POpkixDJdoR7nHF8iOmcPMw==

# Networking
EXPOSE ${PORT}/tcp
EXPOSE ${PORT}/udp

# Run
ENTRYPOINT [ "node ././authorization_server/src/index.js" ]