### Retrieve access token and refresh token

POST http://localhost:8081/auth/server
Authorization: Bearer 06gunn7N8grlHzghZ+1KcZc+YyNCfLM63f0sxoZc6Mb/bd7pXT9ynTRy6emlFCBkoQZixLYh5NAl4/UkQqN+rw==

###

### Check access token

GET http://localhost:8081/auth/server/check-access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjA2Z3VubjdOOGdybEh6Z2haKzFLY1pjK1l5TkNmTE02M2Ywc3hvWmM2TWIvYmQ3cFhUOXluVFJ5NmVtbEZDQmtvUVppeExZaDVOQWw0L1VrUXFOK3J3PT0iLCJpYXQiOjE2NzAzNTg1NDIsImV4cCI6MTY3MDM1ODU1N30.-H9QZP0UfVth731U4niuh91O1htTnJfZFeTKR1LcWL4

###

### Logout route

POST http://localhost:8081/auth/server/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjA2Z3VubjdOOGdybEh6Z2haKzFLY1pjK1l5TkNmTE02M2Ywc3hvWmM2TWIvYmQ3cFhUOXluVFJ5NmVtbEZDQmtvUVppeExZaDVOQWw0L1VrUXFOK3J3PT0iLCJpYXQiOjE2NzAzNTg1NjR9.GY9WNnSrwdhY1Ju1C3p9dBfI5bS2cpmHlkpAvF3ZVtQ

###