# Docker compose for local testing/prod database
services:
  database:
    image: mongo:latest
    container_name: mongodb-LOSS
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/home/deb/docker-volumes/mongodb-LOSS-volume

volumes:
  db-data:
    name: mongodb-LOSS-volume