### Create a new collection and write data

POST http://127.0.0.1:8080/rs/datastore/create-new
Content-Type: application/json

{
	"dbName": "example-db",
	"dbData": {
		"dbID": "ID",
		"dbKey": "dbValue",
		"dbArray": ["index-1", "index-2"]
	}
}

###

### Retreive data from a collection

GET http://127.0.0.1:8080/rs/datastore/fetch-data
Content-Type: application/json

{
	"dbName": "example-db",
	"dbQuery": {"dbID": "ID"},
	"dbQueryOptions": {}
}

###

### Edit data in a collection

PUT http://127.0.0.1:8080/rs/datastore/edit-data
Content-Type: application/json

{
	"dbEditMode": "update",
	"dbName": "example-db",
	"dbData": {"$set": {"dbKey": "value-updated"}},
	"dbQuery": {"dbID": "ID"}
}

###

### Replace data in a collection

PUT http://127.0.0.1:8080/rs/datastore/edit-data
Content-Type: application/json

{
	"dbEditMode": "replace",
	"dbName": "example-db",
	"dbData": {"newData": "yep"},
	"dbQuery": {"dbID": "ID"}
}

###