### Create a new collection and write data

POST http://127.0.0.1:8080/rs/datastore/create-new
Content-Type: application/json

{
	"dbName": "example-db",
	"dbData": {
		"dbTitle": "Player_UUID",
		"dbData": ["my_inv", "my_stats"]
	}
}

###

### Retreive data from a collection

GET http://127.0.0.1:8080/rs/datastore/fetch-data
Content-Type: application/json

{
	"dbName": "example-db",
	"dbQuery": {"dbTitle": "Player_UUID"},
	"dbQueryOptions": {}
}

###