FROM node:hydrogen-slim

# Configuration
ENV LISTEN_PORT=36210

# Copy files
COPY ./build /app

# Chnage workdir
WORKDIR /app

# Expose port
EXPOSE ${LISTEN_PORT}/tcp

# Run
ENTRYPOINT [ "npm", "run", "start-authorization-server" ]