// Imports
import express from 'express'
import { createServer } from 'https'
import { config } from 'dotenv'
import { join } from 'path'
import { returnHTTPSCredentials } from '../../../../shared/general-utility-module/src/general_utility_module'
import { log, wrn } from '../../../../shared/logging-module/src/logging_module'
let _environmentLoadingError: Error | undefined = config({path: join(process.cwd(), './.env/.lossConfig.env')}).error


// Docstring
/**
 * Loopware Online Subsystem @ Analytics Server || Manages the reading and writing of any analytical data generated by
 * Loss services. DO NOT EXPOSE TO THE PUBLIC INTERNET. THIS HAS NO IP BLACKLISTING
 */

// Enums

// Interface

// Constants
const app = express()

// ENV Constants
const PORT: number = Number(process.env.ANALYTICS_LISTEN_PORT)
const PASSPHRASE: string = String(process.env.HTTPS_CERT_PASSPHRASE)

// Public Variables

// Private Variables

// _init()
function _init(): void{
	// Sanity Checks
	if (_environmentLoadingError != undefined){ wrn(`.ENV file was not successfully loaded | ${_environmentLoadingError.message}`) }

	// Enable JSON parsing express middleware
	app.use(express.json())

	// Log all incoming connections to the server
	app.use((req, _res, next) => {
		log(`New "${req.protocol.toUpperCase()}" connection to "${req.baseUrl + req.url}" from "${req.ip}" using "${req.method.toUpperCase()}"`)
		next()
	})

	// Setup routing
	const _analyticsEndpoint = require('./routes/analytics')
	app.use("/analytics/api/v1/", _analyticsEndpoint)

	// Obtain credentials
	let credentialData: object | any = returnHTTPSCredentials(join((process.cwd()), './keys'))
	let credentials: object = {
		key: credentialData.key,
		cert: credentialData.cert,
		passphrase: PASSPHRASE,
	}

	// Start listening
	createServer(credentials, app).listen(PORT, () => {
		log(`LOSS @ Analytics-Server started! || Listening on port ${PORT}`)
	})	
}

// Public Methods

// Private Methods

// Run
_init()