# /**
# * Loopware Online Subsystem @ UDP punchthrough Docker compose file || Simple docker compose file that allows for the creation of
# * a Redis cache instance for storing UDP related data idk
# */

services:
  # Net/UDP Punchthrough
  netRedisDBUDPPunchthroughCache:
    image: redis:latest
    container_name: loss-net-udp-punchthrough-cache-redis
    command: "redis-server --port 36203"
    ports:
      - "36203:36203"
    restart: unless-stopped