name: "Loss Code Checker"

on: pull_request

jobs:
  loss-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      