# /**
# * Loopware Online Subsystem @ AuthDB Dockerfile || Simple dockerfile that allows for the creation of
# * a MongoDB instance for storing ClientIDs and RefreshTokens
# * TODO: Implement a way of scaling
# */

services:
  mongoDBAuthStorage:
    image: mongo:latest
    container_name: loss-authorization-storage-mongo
    command: "mongod --port 36200"
    environment:
      # It is adviced to change the default username and password
      - MONGO_INITDB_ROOT_USERNAME=lossAuthMongoDB
      - MONGO_INITDB_ROOT_PASSWORD=lossAuthMongoDB
    volumes:
      - authorizationStorageVolume:/lossAuthorizationDB:rw
    ports:
      - "36200:36200"
    restart: always

volumes:
  authorizationStorageVolume:
    name: loss-authorization-storage-volume
